global:
  resolve_timeout: 30s

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8017950310:AAEMaZRFwEOH1gp2oo9DsI9gZyGdlZJwdls'
        chat_id: 7365203276
        message: |
          🚨 *Alerta en Prometheus*
          Estado: {{ .Status }}
          Alerta: {{ .CommonLabels.alertname }}
          Instancia: {{ .CommonLabels.instance }}
          Descripción: {{ .CommonAnnotations.summary }}
        parse_mode: "Markdown"
